### ISSUE TITLE
Auto-Configuration Error: Cannot find gcc or CC (gcc-10); either correct your path or set the CC environment variable

### ISSUE THREAD

**Issue by Chanrom** [microsoft/DeepGNN#35]
Hi,

I'm trying to build package from source but met below error. Did I miss something?
```
bazel build -c opt //src/cc/lib:* --config=linux
WARNING: Output base '/home/qiazhou/.cache/bazel/_bazel_qiazhou/36697635938d63babed7c41d12592031' is on NFS. This may lead to surprising failures and undetermined behavior.
Starting local Bazel server and connecting to it...
INFO: Repository local_config_cc instantiated at:
  /DEFAULT.WORKSPACE.SUFFIX:519:13: in <toplevel>
  /home/qiazhou/.cache/bazel/_bazel_qiazhou/36697635938d63babed7c41d12592031/external/bazel_tools/tools/cpp/cc_configure.bzl:184:16: in cc_configure
Repository rule cc_autoconf defined at:
  /home/qiazhou/.cache/bazel/_bazel_qiazhou/36697635938d63babed7c41d12592031/external/bazel_tools/tools/cpp/cc_configure.bzl:145:30: in <toplevel>
ERROR: An error occurred during the fetch of repository 'local_config_cc':
   Traceback (most recent call last):
        File "/home/qiazhou/.cache/bazel/_bazel_qiazhou/36697635938d63babed7c41d12592031/external/bazel_tools/tools/cpp/cc_configure.bzl", line 127, column 33, in cc_autoconf_impl
                configure_unix_toolchain(repository_ctx, cpu_value, overriden_tools)
        File "/home/qiazhou/.cache/bazel/_bazel_qiazhou/36697635938d63babed7c41d12592031/external/bazel_tools/tools/cpp/unix_cc_configure.bzl", line 345, column 17, in configure_unix_toolchain
                cc = find_cc(repository_ctx, overriden_tools)
        File "/home/qiazhou/.cache/bazel/_bazel_qiazhou/36697635938d63babed7c41d12592031/external/bazel_tools/tools/cpp/unix_cc_configure.bzl", line 310, column 23, in find_cc
                cc = _find_generic(repository_ctx, "gcc", "CC", overriden_tools)
        File "/home/qiazhou/.cache/bazel/_bazel_qiazhou/36697635938d63babed7c41d12592031/external/bazel_tools/tools/cpp/unix_cc_configure.bzl", line 306, column 32, in _find_generic
                auto_configure_fail(msg)
        File "/home/qiazhou/.cache/bazel/_bazel_qiazhou/36697635938d63babed7c41d12592031/external/bazel_tools/tools/cpp/lib_cc_configure.bzl", line 112, column 9, in auto_configure_fail
                fail("\n%sAuto-Configuration Error:%s %s\n" % (red, no_color, msg))
Error in fail: 
Auto-Configuration Error: Cannot find gcc or CC (gcc-10); either correct your path or set the CC environment variable
ERROR: /DEFAULT.WORKSPACE.SUFFIX:519:13: fetching cc_autoconf rule //external:local_config_cc: Traceback (most recent call last):
        File "/home/qiazhou/.cache/bazel/_bazel_qiazhou/36697635938d63babed7c41d12592031/external/bazel_tools/tools/cpp/cc_configure.bzl", line 127, column 33, in cc_autoconf_impl
                configure_unix_toolchain(repository_ctx, cpu_value, overriden_tools)
        File "/home/qiazhou/.cache/bazel/_bazel_qiazhou/36697635938d63babed7c41d12592031/external/bazel_tools/tools/cpp/unix_cc_configure.bzl", line 345, column 17, in configure_unix_toolchain
                cc = find_cc(repository_ctx, overriden_tools)
        File "/home/qiazhou/.cache/bazel/_bazel_qiazhou/36697635938d63babed7c41d12592031/external/bazel_tools/tools/cpp/unix_cc_configure.bzl", line 310, column 23, in find_cc
                cc = _find_generic(repository_ctx, "gcc", "CC", overriden_tools)
        File "/home/qiazhou/.cache/bazel/_bazel_qiazhou/36697635938d63babed7c41d12592031/external/bazel_tools/tools/cpp/unix_cc_configure.bzl", line 306, column 32, in _find_generic
                auto_configure_fail(msg)
        File "/home/qiazhou/.cache/bazel/_bazel_qiazhou/36697635938d63babed7c41d12592031/external/bazel_tools/tools/cpp/lib_cc_configure.bzl", line 112, column 9, in auto_configure_fail
                fail("\n%sAuto-Configuration Error:%s %s\n" % (red, no_color, msg))
Error in fail: 
Auto-Configuration Error: Cannot find gcc or CC (gcc-10); either correct your path or set the CC environment variable
INFO: Repository boost instantiated at:
  /vc_data/users/qiazhou/gnn/code/gat/source_build/DeepGNN/WORKSPACE:141:11: in <toplevel>
  /home/qiazhou/.cache/bazel/_bazel_qiazhou/36697635938d63babed7c41d12592031/external/com_github_nelhage_rules_boost/boost/boost.bzl:209:21: in boost_deps
Repository rule http_archive defined at:
  /home/qiazhou/.cache/bazel/_bazel_qiazhou/36697635938d63babed7c41d12592031/external/bazel_tools/tools/build_defs/repo/http.bzl:353:31: in <toplevel>
INFO: Repository snark_com_google_absl instantiated at:
  /vc_data/users/qiazhou/gnn/code/gat/source_build/DeepGNN/WORKSPACE:101:13: in <toplevel>
Repository rule http_archive defined at:
  /home/qiazhou/.cache/bazel/_bazel_qiazhou/36697635938d63babed7c41d12592031/external/bazel_tools/tools/build_defs/repo/http.bzl:353:31: in <toplevel>
INFO: Repository mimalloc instantiated at:
  /vc_data/users/qiazhou/gnn/code/gat/source_build/DeepGNN/WORKSPACE:120:13: in <toplevel>
Repository rule http_archive defined at:
  /home/qiazhou/.cache/bazel/_bazel_qiazhou/36697635938d63babed7c41d12592031/external/bazel_tools/tools/build_defs/repo/http.bzl:353:31: in <toplevel>
INFO: Repository com_github_google_glog instantiated at:
  /vc_data/users/qiazhou/gnn/code/gat/source_build/DeepGNN/WORKSPACE:51:13: in <toplevel>
Repository rule http_archive defined at:
  /home/qiazhou/.cache/bazel/_bazel_qiazhou/36697635938d63babed7c41d12592031/external/bazel_tools/tools/build_defs/repo/http.bzl:353:31: in <toplevel>
ERROR: /vc_data/users/qiazhou/gnn/code/gat/source_build/DeepGNN/src/cc/lib/BUILD:6:10: //src/cc/lib:wrapper depends on @local_config_cc//:cc-compiler-k8 in repository @local_config_cc which failed to fetch. no such package '@local_config_cc//': 
Auto-Configuration Error: Cannot find gcc or CC (gcc-10); either correct your path or set the CC environment variable
ERROR: Analysis of target '//src/cc/lib:wrapper' failed; build aborted: Analysis failed
INFO: Elapsed time: 7.276s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (47 packages loaded, 238 targets configured)
    Fetching https://boostorg.jfrog.io/artifactory/main/release/1.76.0/source/boost_1_76_0.tar.gz
```

**Comment by Chanrom** [comment]
I solved this issue by installing gcc-10 as well:

https://askubuntu.com/questions/1192955/how-to-install-g-10-on-ubuntu-18-04
